### ISSUE TITLE
3. Custom Audio Driver doesn't work

### ISSUE THREAD

**Issue by tankadesign** [opentok/opentok-ios-sdk-samples-swift#13]
Tested this with subscribeToSelf = true and false, and neither works. It would seem the subscriber never joins the session, presumably because the audioDevice never completes getting setup. When switching back to the Objective-C version of this it works no problem.

**Comment by Lucashuang0802** [comment]
Hi @tankadesign, thanks for submitting the issue. In order to let the subscriber join, you should first receive 'streamCreated'. Did that delegate method get called or any errors?

**Comment by tankadesign** [comment]
It gets called on one of the devices - I'm not using standalone mode. After about a minute the stream gets destroyed automatically. The devices I have tested on are: iPhone 6 with iOS 9.3.2, iPhone 7 with 10.3.1 and iPhone 7+ with 10.3.1. On the 7+ I get the Subscriber joining when not in standalone. But not on the iPhone 6 or 7. It doesn't matter which phone I start up first, it's always the same.

When I run it in standalone on the iPhone 6 or 7 (not Plus) I get errors:
Session connected
2017-04-13 14:52:35.709429-0400 3.Custom-Audio-Driver[6576:1664635] Metal GPU Frame Capture Enabled
2017-04-13 14:52:35.709764-0400 3.Custom-Audio-Driver[6576:1664635] Metal API Validation Enabled
2017-04-13 14:52:35.800761-0400 3.Custom-Audio-Driver[6576:1664635] libMobileGestalt MobileGestaltSupport.m:153: pid 6576 (3.Custom-Audio-Driver) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-04-13 14:52:35.800804-0400 3.Custom-Audio-Driver[6576:1664635] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
2017-04-13 14:52:35.873205-0400 3.Custom-Audio-Driver[6576:1664635] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-04-13 14:52:35.874101-0400 3.Custom-Audio-Driver[6576:1664635] [MC] Reading from public effective user settings.
2017-04-13 14:52:36.495475-0400 3.Custom-Audio-Driver[6576:1664635] [Common] _BSMachError: port a903; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2017-04-13 14:52:36.496984-0400 3.Custom-Audio-Driver[6576:1664635] [Common] _BSMachError: port a903; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2017-04-13 14:52:40.480849-0400 3.Custom-Audio-Driver[6576:1664699] [aurioc] 892: failed: -66635 (enable 3, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,      0 Hz, Float32>)

**Comment by Lucashuang0802** [comment]
@tankadesign what do you mean by standalone? Under non-standalone mode, you said the stream gets destroyed automatically. Did you receive any errors that caused this? More information would be helpful 😃

**Comment by tankadesign** [comment]
In my tests:
User A = iPhone 6 or 7
User B = iPhone 7+

* User A joins session & User B joins session ok
* Both users publish to the session
* User B receives the User A's video stream without audio (OTSessionDelegate streamCreated call fires)
* User B never receives OTPublisherDelegate streamCreated call
* User A never receives User B's video; no OTSubscriber or OTSession delegate calls fire after User A publisher joins session and User B subscriber view is removed
* After about 45-60 seconds User B receives OTSessionDelegate streamDestroyed call

It seems that the custom AudioDevice never tells the publisher delegate to fire.

Has anyone actually tested this code? I can't see why it would happen to just me, since I have multiple devices I'm testing on.

**Comment by tankadesign** [comment]
The problem I described above comes from trying to use DefaultAudioDevice in example #2, by the way. So I'm guessing the DefaultAudioDevice isn't really built out enough to work with a custom capturer?

When I run just example #3, I get both streams connecting ok, but the audio never starts so there's never any sound. After about 60 seconds again (same as above) one of the streams gets destroyed and the other device crashes at line 295 of DefaultAudioDevice.swift:
`let result = AudioOutputUnitStart(playoutVoiceUnit!)`

debug output:
`Destoying audio units
Error reseting AVAudioSession
OTPublisherDelegate streamDestroyed
fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by robjperez** [comment]
With this [PR](https://github.com/opentok/opentok-ios-sdk-samples-swift/pull/25) it should be fixed.

**Comment by alexsafe** [comment]
I am still getting this issue. I am using swift 4, did the appropriate changes to the master branch, but i am using the DefaultAudioDevice class in my own project. Has this been reported again, or maybe it's something wrong with the way i call the class?
