### ISSUE TITLE
 the latest iOS OpenTok SDK( 2.19.0) crash: Collection <NSDictionaryM: 0x28178b2c0> was mutated while being enumerated

### ISSUE THREAD

**Issue by Lebron1992** [opentok/opentok-ios-sdk-samples-swift#146]
When the host, celebrity and fan are online, if we kick the fan and then kick the host right away from [IBS](https://github.com/opentok/interactive-broadcast-js), the iOS app using `OpenTok(2.19.0) ` will crash with a big probability. But the `version 2.18.1` works great! The crash error message is: `Collection <NSDictionaryM: 0x28178b2c0> was mutated while being enumerated.`
We printed out the object `Collection <NSDictionaryM: 0x28178b2c0> `, it shown that:

```
{
    "44B646E2-178E-4859-95E2-F4F254A51EAF" = "<OTSubscriber: 0x2814b1ef0>";
    "BEEFA58C-8768-4CAD-AB66-94D3B71BCAD2" = "<OTSubscriber: 0x2814a40f0>";
}
```

Stack trace:
![WechatIMG42](https://user-images.githubusercontent.com/13708531/110289180-053d1800-8024-11eb-9134-b7424c5eee8b.jpeg)

We haven't store the subscribers as the structure above in our code. So we thought the crash was from OpenTok SDK.

Could you check the SDK code? Thanks!

**Comment by lucas-tl** [comment]
@willyaranda is this in your radar? I am seeing a surge of this crash. The SDK version is 2.19.0.

**Comment by enasaz9** [comment]
same happened with me

**Comment by lucas-tl** [comment]
@jvalli @mheap @abdulajet can you perhaps take a look at this crash? It's critical and it has been an issue for over a month. We have impact in production for a massive number of users.

**Comment by abdulajet** [comment]
version 2.19.1 is out now, which should fix this crash. can you give it a go @lucas-tl ?

**Comment by DusanStjepanovic** [comment]
@abdulajet  We are still getting this crash on 2.19.1 for 5% of users, so it really is critical, had to revert to 2.18.1. We did not manage to reproduce it but here is crash report
<img width="606" alt="Screenshot 2021-04-21 at 09 38 39" src="https://user-images.githubusercontent.com/57255694/115515853-d0a8b700-a285-11eb-9d95-1c90583a5618.png">

**Comment by lucas-tl** [comment]
@abdulajet Adding some context just in case it helps. In our case, the crash occurs when another user in the video call stops sharing their screen. There seems to be no problem and screensharing seems to work just fine before that point. So, it's the "stop screen sharing" what seems to be triggering it.

**Comment by abdulajet** [comment]
Can you try 2.20.0

**Comment by DusanStjepanovic** [comment]
We still have this issue with 2.20.0. To be fair it happens less frequently, but still we had 27 crashes this week.

**Comment by abdulajet** [comment]
@DusanStjepanovic can you share a trace or file a support ticket please https://support.tokbox.com/hc/en-us
